[cherry-pick] [bugfix] Fixing the TableType val passed for unavailable segments in physical optimizer (#16660)
Summary:
PR: https://github.com/apache/pinot/pull/16660

An issue was discovered while querying a table with unavailable segments with the physical optimizer enabled.
```
Error Code: 150 (SQLParsingError)

SQLParsingError: Error composing query plan: No enum constant org.apache.pinot.spi.config.table.TableType.my_table_name.
```
This was due to the tableName incorrectly passed instead of tableType for `TableType.valueOf()`.

Will be merged on release-1.4.x.

Test Plan:
Test details here: https://docs.google.com/document/d/1so2a2W8EuAAoaVbXNS_RngvOtcJcb1DR0-4P2iOuMok/edit?tab=t.gmq6gzr2yz40

Reviewers: #ldap_rta-group, ureview, xuanyili, ankitsultana

Reviewed By: #ldap_rta-group, xuanyili, ankitsultana

Subscribers: xuanyili

Tags: #has_java

JIRA Issues: EVA-12074

Differential Revision: https://code.uberinternal.com/D19717457